roles:
  - src: https://github.com/digimokan/ans_role_add_group
  - src: https://github.com/digimokan/ans_role_add_user
  - src: https://github.com/digimokan/ans_role_config_automatic_printing
  - src: https://github.com/digimokan/ans_role_config_automatic_scanning
  - src: https://github.com/digimokan/ans_role_config_bash
  - src: https://github.com/digimokan/ans_role_config_boot_messages
  - src: https://github.com/digimokan/ans_role_config_chromium
  - src: https://github.com/digimokan/ans_role_config_firefox
  - src: https://github.com/digimokan/ans_role_config_fonts
  - src: https://github.com/digimokan/ans_role_config_libreoffice
  - src: https://github.com/digimokan/ans_role_config_mate_de
  - src: https://github.com/digimokan/ans_role_config_sound
  - src: https://github.com/digimokan/ans_role_config_simple_scan
  - src: https://github.com/digimokan/ans_role_config_sudo
  - src: https://github.com/digimokan/ans_role_config_tarsnap
  - src: https://github.com/digimokan/ans_role_config_time
  - src: https://github.com/digimokan/ans_role_config_unofficial_packages
  - src: https://github.com/digimokan/ans_role_config_upgrades
  - src: https://github.com/digimokan/ans_role_config_video_drivers
  - src: https://github.com/digimokan/ans_role_config_vlc
  - src: https://github.com/digimokan/ans_role_config_xdg_user_dirs
  - src: https://github.com/digimokan/ans_role_config_xdm_dm
  - src: https://github.com/digimokan/ans_role_cpu_microcode
  - src: https://github.com/digimokan/ans_role_pacnew_ignore

